### PR TITLE
add images in next-gen formats

### PR DESCRIPTION
**Pull request by MohcineDev**
add images in next-gen formats to help your website to load faster

Image formats like WebP and AVIF often provide better compression than PNG or JPEG, which means faster downloads and less data consumption

check your page speed insights here : https://developers.google.com/speed/pagespeed/insights/?url=aichalaafia.me%2F

### CODE REVIEW

**Comment by alaafia** [comment]
I will keep that in mind for the next projects, thank you Mohcine.

**Review by alaafia — COMMENTED** [review]
No more png & jpg and say hello to the webp then

**Review by alaafia — COMMENTED** [review]
thanks for organizing it.

**Comment by MohcineDev** [comment]
you're welcome 
you can use this tool or contact me https://developers.google.com/speed/webp

**Pull request merged**
